Repository svd-system/svd-system-api, pull requests merged in 2020-06, with the labels that each got.

#13 Cadastro de vacina
  docs/vaccine.yaml
  src/controllers/index.js
  src/controllers/vaccine.js
  src/models/migrations/20200606193432-create-vaccine.js
  src/models/vaccine.js
  src/routes/index.js
  src/routes/vaccine.js
  src/validators/index.js
  src/validators/vaccine.js
Labels: enhancement

#14 Registro de vacinas
  docs/vaccination.yaml
  src/controllers/index.js
  src/controllers/vaccination-record.js
  src/models/migrations/20200606233746-create-vaccination-record.js
  src/models/vaccination-record.js
  src/routes/index.js
  src/routes/user.js
  src/routes/vaccination-record.js
  src/validators/index.js
  src/validators/vaccination-record.js
Labels: enhancement

#15 newsfeed
  docs/newsfeed.yaml
  docs/vaccine.yaml
  package-lock.json
  package.json
  src/app.js
  src/controllers/index.js
  src/controllers/newsfeed.js
  src/controllers/vaccine.js
  src/models/index.js
  src/models/migrations/20200608015659-create-newsfeed.js
  src/models/newsfeed.js
  src/routes/index.js
  src/routes/newsfeed.js
  src/routes/vaccine.js
  src/validators/index.js
  src/validators/newsfeed.js
  src/validators/vaccine.js
Labels: enhancement

#16 Adicionar o Sequelize CLI como dependencia de produção
  package.json
Labels: bug

#17 Gerar chaves pública e privada para autenticação
  package.json
Labels: bug

#18 Remover validação da senha do usuário no registro da vacina
  docs/vaccination.yaml
  src/controllers/vaccination-record.js
  src/validators/vaccination-record.js
Labels: bug

#20 Ajuste na criação e atualização de vacinas
  src/controllers/login.js
  src/controllers/vaccine.js
  src/validators/vaccination-record.js
  src/validators/vaccine.js
Labels: bug

#21 Ordenar posts do mural de maneira decrescente
  src/controllers/newsfeed.js
Labels: bug, enhancement
